### PR TITLE
Test suite

### PR DESCRIPTION
**Pull request by dmcclean**
Restructuring cabal file and repository layout to play nicely with the way cabal wants to run test suites these days.

Advantage is that it gets the tests into a form where they can be run by `cabal test` and therefore by travis.

### CODE REVIEW

**Comment by dmcclean** [comment]
Leaving this as a PR for @bjornbm to look at, in case he has any objections to the fact that it moves everything one directory lower under `src`.

**Comment by bjornbm** [comment]
If this is the way the community wants projects structured then we might as well play along.

Looks like Travis ran the tests; nice! Is it ossible to get test output to not be lost in a log file (by an appropriate cabal flag?)?

**Comment by dmcclean** [comment]
No to the `sdist` question, but it's because I goofed and forgot to add the other two, other than the main one, to `other-modules`. Just pushed a fix, which I verified includes all three in the `sdist`. They only get `cabal install`ed if you `--enable-tests` though, along with the extra dependencies like `HUnit`.

I'm not sure how to get travis to be more friendly about where it puts results of this kind of analysis. I'll look into it.

**Comment by bjornbm** [comment]
The Travis log says:




> Test suite logged to: dist/test/dimensional-dk-0.8.0.1-tests.log





I think the dist directory is a cabal directory so it is probably cabal who decides to log to file. I was thinking maybe cabal has a flag to log to console instead, in which case I presume it would show up in the Travis log?

**Comment by dmcclean** [comment]
I think we've got that now, see if this is what you meant.

**Comment by bjornbm** [comment]
That looks just right. :)

**Pull request merged**
